# 修复一个被忽视的 bug，星期二，2 月 7 日

顺便说一句，这个版本修复了我们之前在 FLANG 的替换版本中遇到的一个 bug：

```
(run "{with {f {fun {y} {+ x y}}}        {with {x 7}          {call f 1}}}")
```

这个 bug 是由于我们天真的 `subst` 导致的，它没有避免捕获重命名。但请注意，由于评估器的这个版本是从外部到内部的，对于*有效*程序（即没有自由标识符的程序），语义上没有区别。

（提醒：这*不是*一个动态作用域的语言，只是一个 bug，在 `x` 在 `f` 被替换为引用 `x` 之前没有被替换掉时发生。）
